# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Gamma_func2p_pic_cpp <- function(id, x, L, R, d, beta) {
    .Call(`_aftPenCDA_Gamma_func2p_pic_cpp`, id, x, L, R, d, beta)
}

est_funcp_pic_cpp <- function(ei, ej, xij, si, mi, mj, z_in = NULL) {
    .Call(`_aftPenCDA_est_funcp_pic_cpp`, ei, ej, xij, si, mi, mj, z_in)
}

un_est_funcp_pic_cpp <- function(ei, ej, xij, si, mi, mj, z) {
    .Call(`_aftPenCDA_un_est_funcp_pic_cpp`, ei, ej, xij, si, mi, mj, z)
}

Gamma_funcp_pic_cpp <- function(ei, ej, xij, si, mi, mj, B = 200L) {
    .Call(`_aftPenCDA_Gamma_funcp_pic_cpp`, ei, ej, xij, si, mi, mj, B)
}

up_Amatp_pic_cpp <- function(ei, ej, xij, si, mi, mj) {
    .Call(`_aftPenCDA_up_Amatp_pic_cpp`, ei, ej, xij, si, mi, mj)
}

Sigma_funcp_pic_cpp <- function(ei, ej, xij, Gamma, si, mi, mj) {
    .Call(`_aftPenCDA_Sigma_funcp_pic_cpp`, ei, ej, xij, Gamma, si, mi, mj)
}

Sigma_funcp_pen_pic_cpp <- function(ei, ej, xij, Gamma, si, mi, mj, n, tilde_beta, lambda) {
    .Call(`_aftPenCDA_Sigma_funcp_pen_pic_cpp`, ei, ej, xij, Gamma, si, mi, mj, n, tilde_beta, lambda)
}

sifunc_pic_cpp <- function(xij, Sigma) {
    .Call(`_aftPenCDA_sifunc_pic_cpp`, xij, Sigma)
}

is_aftp_pic_cpp <- function(dt, se, beta_in = NULL, maxit = 10L, tol = 1e-2) {
    .Call(`_aftPenCDA_is_aftp_pic_cpp`, dt, se, beta_in, maxit, tol)
}

est_func_pic_cpp <- function(ei, ej, xij, eta2i, eta1j, si) {
    .Call(`_aftPenCDA_est_func_pic_cpp`, ei, ej, xij, eta2i, eta1j, si)
}

un_est_func_pic_cpp <- function(ei, ej, xij, eta2i, eta1j, si, z) {
    .Call(`_aftPenCDA_un_est_func_pic_cpp`, ei, ej, xij, eta2i, eta1j, si, z)
}

up_Amat_pic_cpp <- function(ei, ej, xij, eta2i, eta1j, si) {
    .Call(`_aftPenCDA_up_Amat_pic_cpp`, ei, ej, xij, eta2i, eta1j, si)
}

Gamma_func_pic_cpp <- function(ei, ej, xij, eta2i, eta1j, si, B = 200L) {
    .Call(`_aftPenCDA_Gamma_func_pic_cpp`, ei, ej, xij, eta2i, eta1j, si, B)
}

Gamma_func2_pic_cpp <- function(dt, beta) {
    .Call(`_aftPenCDA_Gamma_func2_pic_cpp`, dt, beta)
}

Sigma_func_pic_cpp <- function(ei, ej, xij, eta2i, eta1j, Gamma, si) {
    .Call(`_aftPenCDA_Sigma_func_pic_cpp`, ei, ej, xij, eta2i, eta1j, Gamma, si)
}

Sigma_func_pen_pic_cpp <- function(ei, ej, xij, eta2i, eta1j, Gamma, si, tilde_beta, lambda) {
    .Call(`_aftPenCDA_Sigma_func_pen_pic_cpp`, ei, ej, xij, eta2i, eta1j, Gamma, si, tilde_beta, lambda)
}

is_aft_pic_cpp <- function(dt, se) {
    .Call(`_aftPenCDA_is_aft_pic_cpp`, dt, se)
}

Gamma_func2_cpp <- function(e, x, d) {
    .Call(`_aftPenCDA_Gamma_func2_cpp`, e, x, d)
}

un_est_func_cpp <- function(ei, ej, xij, di, z) {
    .Call(`_aftPenCDA_un_est_func_cpp`, ei, ej, xij, di, z)
}

est_func_cpp <- function(ei, ej, xij, di, si) {
    .Call(`_aftPenCDA_est_func_cpp`, ei, ej, xij, di, si)
}

Gamma_func_cpp <- function(ei, ej, xij, di, si, B = 200L) {
    .Call(`_aftPenCDA_Gamma_func_cpp`, ei, ej, xij, di, si, B)
}

up_Amat_cpp <- function(ei, ej, xij, di, si) {
    .Call(`_aftPenCDA_up_Amat_cpp`, ei, ej, xij, di, si)
}

Sigma_func_cpp <- function(ei, ej, xij, di, Gamma, si) {
    .Call(`_aftPenCDA_Sigma_func_cpp`, ei, ej, xij, di, Gamma, si)
}

Sigma_func_pen_cpp <- function(ei, ej, xij, di, Gamma, si, tilde_beta, lambda) {
    .Call(`_aftPenCDA_Sigma_func_pen_cpp`, ei, ej, xij, di, Gamma, si, tilde_beta, lambda)
}

sifunc_cpp <- function(xij, Sigma) {
    .Call(`_aftPenCDA_sifunc_cpp`, xij, Sigma)
}

weighted_lm_cpp <- function(y, x, d) {
    .Call(`_aftPenCDA_weighted_lm_cpp`, y, x, d)
}

is_aft_cpp <- function(y, d, x, se_type = "") {
    .Call(`_aftPenCDA_is_aft_cpp`, y, d, x, se_type)
}

Sigma_func_stable_cpp <- function(ei, ej, xij, di, Gamma, si, stable_numb1) {
    .Call(`_aftPenCDA_Sigma_func_stable_cpp`, ei, ej, xij, di, Gamma, si, stable_numb1)
}

is_aft_stable_cpp <- function(y, d, x, stable_numb1, se_type = "") {
    .Call(`_aftPenCDA_is_aft_stable_cpp`, y, d, x, stable_numb1, se_type)
}

